#ifndef EMBB_CONTAINERS_INTERNAL_CACHE_H_
#define EMBB_CONTAINERS_INTERNAL_CACHE_H_


#define EMBB_CONTAINERS_CACHE_ALIGN

#ifndef EMBB_DATA_CACHE_LINE_SIZE
# define EMBB_CONTAINERS_CACHE_LINE_SIZE 64
#endif

#ifdef __GNUC__
# ifndef EMBB_CONTAINERS_CACHE_ALIGN
#  define EMBB_CONTAINERS_CACHE_ALIGN __attribute__ ((aligned (EMBB_DATA_CACHE_LINE_SIZE)))
# endif
# ifndef EMBB_CONTAINERS_VAR_ALIGN
#  define EMBB_CONTAINERS_VAR_ALIGN   __attribute__ ((aligned (16)))
# endif
#elif defined _MSC_VER || defined __INTEL_COMPILER
# ifndef EMBB_CONTAINERS_CACHE_ALIGN
#  define EMBB_CONTAINERS_CACHE_ALIGN __declspec(align(EMBB_CONTAINERS_CACHE_LINE_SIZE)) 
# endif
# ifndef EMBB_CONTAINERS_VAR_ALIGN
#  define EMBB_CONTAINERS_VAR_ALIGN   __declspec(align(64)) 
# endif
#else
# ifndef EMBB_CONTAINERS_CACHE_ALIGN
#  define EMBB_CONTAINERS_CACHE_ALIGN
# endif
#endif

#define EMBB_CONTAINERS_PAD_CACHE(A) ((EMBB_CONTAINERS_CACHE_LINE_SIZE - (A % EMBB_CONTAINERS_CACHE_LINE_SIZE))/sizeof(int32_t))

#endif /* EMBB_CONTAINERS_INTERNAL_CACHE_H_ */
