#ifndef EMBB_CONTAINERS_CPP_INTERNAL_FLAGS_H_
#define EMBB_CONTAINERS_CPP_INTERNAL_FLAGS_H_

#define EMBB_CONTAINERS_DISABLE_CACHE_ALIGN 0
#define EMBB_CONTAINERS_USE_HP_OLD 1

#endif /* EMBB_CONTAINERS_CPP_INTERNAL_FLAGS_H_ */
